### ISSUE TITLE
Semantic Indentation

### ISSUE THREAD

**Issue by dannyfreeman** [clojure-emacs/clojure-ts-mode#9]
Clojure-ts-mode currently only uses a simple fixed indentation style made up of two basic rules taken from Tonsky's blog post on Clojure indentation [0].

- Multi-line lists that start with a symbol are always indented with two spaces,
- Other multi-line lists, vectors, maps and sets are aligned with the first element (1 or 2 spaces).

This was a great way to get clojure-ts-mode off the ground. However, most Clojure developers are adjusted to formatting rules similar to those outlined in the Clojure Style Guide [1].

This ticket is for a feature to allow users to choose between the simple fixed indentation rules that exist now, and semantic indentation rules that match (as closely as possible) those laid out in the Clojure Style Guide.

[0] [Better Clojure Formatting](https://tonsky.me/blog/clojurefmt)
[1] [Clojure Style Guide](https://guide.clojure.style/)

**Comment by dawranliou** [comment]
Hey @dannyfreeman thank you for the great work!  I've been using `clojure-ts-mode` as my daily driver since I saw the announcement blog post.  It solved a pain point for me when working with humongous map literals.  🙏   Would you share how much collaboration you seek for this project?  Would you like bug reports, or do you accept PRs at the current stage of the project?

Just for the people looking for a way to hack the formatting rules to comply with the Clojure Style Guide [1] before this issue #9 is resolved, [here's the relevant code snippet from my config](https://github.com/dawranliou/emacs.d/blob/2dc315e5f187d8e58bbb406c9da993678e754f14/init.el#L776):

```elips
(with-eval-after-load 'clojure-ts-mode
  (require 'clojure-mode)
  (add-hook 'clojure-ts-mode-hook #'clojure-mode-variables)
  ;; ...
  )
```

This sets up many [`clojure-mode`](https://github.com/clojure-emacs/clojure-mode) local variables just as the `clojure-mode` does, most noticeably the code and comment formats.

**Comment by jasonjckn** [comment]
What do we have for prior art, for complex indentation rules, I know https://github.com/mickeynp/combobulate has complex indentation, as I recall, it's doing a lot of calculations crawling the treesit node/graph and working directly with the AST. Is this kind of what we had in mind? Or are there simpler ways to accomplish complex indentation rules.

**Comment by jasonjckn** [comment]
Looking good so far...  do you know if simple indent rules will give us equivalent of 'clojure-align-forms-automatically t' ? 

That's been the biggest usability issue for me with clojure-ts-mode, because I can always use https://github.com/radian-software/apheleia + clojure-ts-mode to regain the cljfmt functionality, but clojure-mode is the only formatter i'm aware of with 'clojure-align-forms-automatically t'

**Comment by jasonjckn** [comment]
I was playing around with lisp-indent-function, and it seems to matter greatly what it is set to... I don't understand why that matters, but beware of it, here's the experiment 

https://github.com/clojure-emacs/clojure-ts-mode/assets/550839/8613f35d-bdb6-4601-8cb5-e95117835133
1080p: https://drive.google.com/file/d/1pzIPoZmHi-xbAZ2ibr-pexufkDIhNGCN/view?usp=drive_link

``` 
(defun my/set-lisp-indent-lisp ()
  (interactive)

  (setq-local
  lisp-indent-function #'lisp-indent-function ; <-----------------

   indent-line-function #'treesit-indent
   indent-region-function #'treesit-indent-region
  ))

(defun my/set-lisp-indent-clojure ()
  (interactive)

  (setq-local
  lisp-indent-function #'clojure-indent-function ; <-----------------

   indent-line-function #'treesit-indent
   indent-region-function #'treesit-indent-region
  ))

(defun my/set-lisp-indent-treesit ()
  (interactive)

  (setq-local
  lisp-indent-function #'treesit-indent ; <-----------------

   indent-line-function #'treesit-indent
   indent-region-function #'treesit-indent-region
  ))
```
